version: '3.8'

services:
  tickethive:
    image: ticket_hive:latest
    container_name: ticket_hive
volumes:
  ticket_hive_data:
      #driver: local
      # this is where it will store the database data
  ticket_hive_logs:
      #driver: local


networks:
  default:
    external:
      name: fabric_test
