# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import Ticket_pb2 as Ticket__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in Ticket_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TicketStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadTicketById = channel.unary_unary(
                '/ticket.Ticket/ReadTicketById',
                request_serializer=Ticket__pb2.ReadTicketByIdRequest.SerializeToString,
                response_deserializer=Ticket__pb2.ReadTicketByIdReply.FromString,
                _registered_method=True)
        self.TransferTicket = channel.unary_unary(
                '/ticket.Ticket/TransferTicket',
                request_serializer=Ticket__pb2.TransferTicketRequest.SerializeToString,
                response_deserializer=Ticket__pb2.TransferTicketReply.FromString,
                _registered_method=True)


class TicketServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReadTicketById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferTicket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TicketServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadTicketById': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadTicketById,
                    request_deserializer=Ticket__pb2.ReadTicketByIdRequest.FromString,
                    response_serializer=Ticket__pb2.ReadTicketByIdReply.SerializeToString,
            ),
            'TransferTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferTicket,
                    request_deserializer=Ticket__pb2.TransferTicketRequest.FromString,
                    response_serializer=Ticket__pb2.TransferTicketReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ticket.Ticket', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ticket.Ticket', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Ticket(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReadTicketById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ticket.Ticket/ReadTicketById',
            Ticket__pb2.ReadTicketByIdRequest.SerializeToString,
            Ticket__pb2.ReadTicketByIdReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ticket.Ticket/TransferTicket',
            Ticket__pb2.TransferTicketRequest.SerializeToString,
            Ticket__pb2.TransferTicketReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
