version: '3.8'

services:
  ticket-transfer:
    build:
      context: .
      dockerfile: Dockerfile
    image: wigsicle/ticket-transfer-app
    container_name: ticket-transfer-app-container
    ports:
      - "50051:50051"
    volumes:
      - type: bind
        source: ./Org1/ca.crt
        target: /app/Org1/ca.crt
      - type: bind
        source: ./Org1/signcerts/User1@org1.example.com-cert.pem
        target: /app/Org1/signcerts/User1@org1.example.com-cert.pem
      - type: bind
        source: ./Org1/keystore/priv_sk
        target: /app/Org1/keystore/priv_sk
    environment:
      - MSP_ID=Org1MSP
      - CRYPTO_PATH=/app
      - CERT_PATH=signcerts/User1@org1.example.com-cert.pem
      - KEY_PATH=keystore/priv_sk
      - TLS_CERT_PATH=ca.crt
      - PEER_ENDPOINT=dns:///peer0.org1.example.com:7051
      - GATEWAY_PEER=peer0.org1.example.com
    command: ["./ticketTransfer"]

networks:
  default:
    external:
      name: fabric_test
