# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Ticket.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'Ticket.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cTicket.proto\x12\x06ticket\")\n\x15ReadTicketByIdRequest\x12\x10\n\x08ticketId\x18\x01 \x01(\t\";\n\x15TransferTicketRequest\x12\x10\n\x08ticketId\x18\x01 \x01(\t\x12\x10\n\x08newOwner\x18\x02 \x01(\t\")\n\x13ReadTicketByIdReply\x12\x12\n\nticketInfo\x18\x01 \x01(\t\"&\n\x13TransferTicketReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xa4\x01\n\x06Ticket\x12L\n\x0eReadTicketById\x12\x1d.ticket.ReadTicketByIdRequest\x1a\x1b.ticket.ReadTicketByIdReply\x12L\n\x0eTransferTicket\x12\x1d.ticket.TransferTicketRequest\x1a\x1b.ticket.TransferTicketReplyB\x0bZ\t./;ticketb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Ticket_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\t./;ticket'
  _globals['_READTICKETBYIDREQUEST']._serialized_start=24
  _globals['_READTICKETBYIDREQUEST']._serialized_end=65
  _globals['_TRANSFERTICKETREQUEST']._serialized_start=67
  _globals['_TRANSFERTICKETREQUEST']._serialized_end=126
  _globals['_READTICKETBYIDREPLY']._serialized_start=128
  _globals['_READTICKETBYIDREPLY']._serialized_end=169
  _globals['_TRANSFERTICKETREPLY']._serialized_start=171
  _globals['_TRANSFERTICKETREPLY']._serialized_end=209
  _globals['_TICKET']._serialized_start=212
  _globals['_TICKET']._serialized_end=376
# @@protoc_insertion_point(module_scope)
